### ISSUE TITLE
causes infinite scrolling

### ISSUE THREAD

**Issue by Haroenv** [bullgit/bullgit-badges#4]
well, not really infinite, but very long

**Comment by Haroenv** [comment]
is fixed if you use https://github.com/bullgit/badge

**Comment by mischah** [comment]
Thanks for the fix. But why don’t you fix it over here?
Or should we delete this repo instead?

**Comment by Haroenv** [comment]
It's a totally different approach, and the original was by @lukyvj, so I'll keep his advice in mind.
